version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=shou
            - POSTGRES_USER=shou
            - POSTGRES_PASSWORD=shou@2021
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home/vanduong/data/work/Shou/
        ports: 
            - "8000:8000"
        depends_on: 
            - db
