# Generated by Django 3.1.7 on 2021-02-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_locationsignedin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationsignedin',
            table='shou_location_signed_in',
        ),
    ]
